version: '3.8'

services:
  db:
    build: db/
    container_name: paperless-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paperlessdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rest:
    build: ./out
    container_name: rest
    restart: no
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paperlessdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password

  ui:
    build: ./ui
    container_name: frontend
    ports:
      - "80:80"
      - "9090:9090"
    depends_on:
      - rest
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # RabbitMQ message broker port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

  minio:
        image: minio/minio:latest
        container_name: minio
        environment:
          MINIO_ROOT_USER: admin           # Set MinIO access key
          MINIO_ROOT_PASSWORD: password    # Set MinIO secret key
        ports:
          - "9000:9000"  # MinIO API Port
          - "9001:9001"  # MinIO Console Port
        volumes:
          - minio_data:/data               # Persist storage
        command: server /data --console-address ":9001"
        networks:
          - app-network

  workers:
    build:
      dockerfile: workers/Dockerfile
    container_name: workers
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    depends_on:
      - rabbitmq
    networks:
      - app-network


volumes:
  postgres_data:
  minio_data: # Persistent storage volume for MinIO
    driver: local

networks:
  app-network:
    driver: bridge








