[project]
name = "workers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "minio>=7.2.15",
    "pdf2image>=1.17.0",
    "pika>=1.3.2",
    "pillow>=11.1.0",
    "pytesseract>=0.3.13",
]
